# Generated by Django 5.2.3 on 2025-07-20 06:17

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerFirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomerLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomerEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('CustomerPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('CustomerAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('CustomerInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('TechID', models.AutoField(primary_key=True, serialize=False)),
                ('TechName', models.CharField(max_length=100)),
                ('TechEmail', models.EmailField(max_length=254, unique=True)),
                ('TechPhone', models.CharField(max_length=15, unique=True)),
                ('TechSpecialization', models.CharField(blank=True, max_length=100, null=True)),
                ('TechAvailability', models.BooleanField(default=True)),
                ('TechInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('AppID', models.AutoField(primary_key=True, serialize=False)),
                ('AppDate', models.DateField(default=django.utils.timezone.now)),
                ('AppStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('AppTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PaymentType', models.CharField(blank=True, max_length=20, null=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100)),
                ('ServiceCode', models.CharField(max_length=20)),
                ('ServiceDescription', models.TextField(blank=True, null=True)),
                ('ServicePrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ServiceStartTime', models.TimeField(default=datetime.time(0, 0))),
                ('ServiceDuration', models.IntegerField(default=30)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Services', to='Main.appointments')),
                ('TechID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.technicians')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserEmail', models.EmailField(max_length=254, unique=True)),
                ('UserPhone', models.CharField(max_length=15, unique=True)),
                ('UserAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('UserSalonName', models.CharField(blank=True, max_length=100, null=True)),
                ('UserInfo', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='technicians',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedServices',
            fields=[
                ('ServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=100)),
                ('ServiceCode', models.CharField(max_length=20)),
                ('ServiceDescription', models.TextField(blank=True, null=True)),
                ('ServicePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ServiceDuration', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointments',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
