# Generated by Django 5.2.3 on 2025-07-24 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='Main.customer'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedservices',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavedServices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='TechID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Technicians', to='Main.technicians'),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Technicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
