# Generated by Django 5.2.3 on 2025-07-01 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='ServiceStartTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
