# Generated by Django 5.2.3 on 2025-07-24 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_appointments_customerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='TechID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Services', to='Main.technicians'),
        ),
    ]
