# Generated by Django 5.2.3 on 2025-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_services_techid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='AppComment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
