# Generated by Django 5.2.3 on 2025-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_appointments_appdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='AppStatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AppTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='PaymentType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='ServiceDuration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='ServicePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
