# Generated by Django 5.2.3 on 2025-07-13 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_appointments_appstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='AppDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
