# Generated by Django 5.2.3 on 2025-07-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_appointments_appcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='TechAvailability',
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('ScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Availability', models.BooleanField()),
                ('TechID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedules', to='Main.technicians')),
            ],
        ),
    ]
