# Generated by Django 5.2.3 on 2025-07-28 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_technicians_techavailability_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='Created_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
