# Generated by Django 5.2.3 on 2025-07-14 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_appointments_appdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserAdditionalInfo',
            new_name='UserInfo',
        ),
        migrations.RemoveField(
            model_name='services',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserRole',
        ),
        migrations.AddField(
            model_name='appointments',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedservices',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='UserSalonName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('TechID', models.AutoField(primary_key=True, serialize=False)),
                ('TechName', models.CharField(max_length=100)),
                ('TechEmail', models.EmailField(max_length=254, unique=True)),
                ('TechPhone', models.CharField(max_length=15, unique=True)),
                ('TechSpecialization', models.CharField(blank=True, max_length=100, null=True)),
                ('TechAvailability', models.BooleanField(default=True)),
                ('TechInfo', models.TextField(blank=True, null=True)),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='TechID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.technicians'),
        ),
    ]
