# Generated by Django 5.2.3 on 2025-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_rename_useradditionalinfo_user_userinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedservices',
            name='ServiceCode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savedservices',
            name='ServiceDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='ServiceCode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='services',
            name='ServiceDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
