# Generated by Django 5.2.3 on 2025-07-29 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_schedules_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('SupplyID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplyName', models.CharField(default='Unnamed Supply')),
                ('Created_At', models.DateTimeField(default=django.utils.timezone.now)),
                ('Last_Modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('Quantity', models.IntegerField(default=0)),
                ('Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
