# Generated by Django 5.2.3 on 2025-07-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_supplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserEmail',
        ),
    ]
