# Generated by Django 5.2.3 on 2025-08-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_user_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserPhone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
