# Generated by Django 5.2.3 on 2025-08-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_user_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='TechEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='TechPhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
