# Generated by Django 5.2.3 on 2026-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_customer_customeremail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AddField(
            model_name='services',
            name='ServiceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
