# Generated by Django 5.2.3 on 2026-02-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_remove_services_id_services_serviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='ServiceComment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
