# Generated by Django 5.2.3 on 2026-02-11 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_services_servicecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerCreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
